class Questionnaires {
  static List<String> lstQuestions = [
    "1) You actively read and understand subjects around you",
    "2) You actively listen to subjects around you",
    "3) You are able to write information subjects clearly",
    "4) You have the speaking ability to convey information clearly",
    "5) You are good at maths",
    "6) You are good at science",
    "7) You are good in critical thinking skill",
    "8) You actively reach out and try to learn subjects surrounding you",
    "9) You are able to strategies how you approach learning subjects",
    "10) You are quite conscious/aware of your surroundings",
    "11) You have a good understanding of social perception",
    "12) You keep track of coordination of where things are surrounding you",
    "13) You are good at persuading people",
    "14) You are good at making negotiation and convincing people",
    "15) You are good at instructing people",
    "16) You tend to give your service to others",
    "17) You love dealing with complex problems",
    "18) You are good at analyzing how things operate at technical level",
    "19) You love designs in technology",
    "20) You are good at selecting how things come together",
    "21) You are good at bringing things together to work",
    "22) You are good at programming things to work as they should",
    "23) You are good at monitoring operations",
    "24) You are good at controlling how operations go",
    "25) You enjoy maintenance especially in equipments",
    "26) You are good at deducing why errors occur or troubleshooting",
    "27) You are good at repairing objects",
    "28) You are good at analyzing quality of given objects",
    "29) You are good at decision and judgement-making",
    "30) You know how to analyze how systems work",
    "31) You are good at giving fair analysis to systems",
    "32) You are good in managing time",
    "33) You are good at managing finances", // lv value 1.25
    "34) You are good at managing materials",
    "35) You are good at managing people", // lv value 2.12
  ];
}